### ISSUE TITLE
select2 support

### ISSUE THREAD

**Issue by huglester** [anomalylabs/select-field_type#6]
Hello,
probably when this https://github.com/anomalylabs/multiple-field_type/pull/20 get merged, we could borrow some code to enable select2 support in here to (maybe optionally?)

Thanks

**Comment by RyanThompson** [comment]
Agreed!

**Comment by RyanThompson** [comment]
Let's open this in the main repository though - prefix it with [select-field_type] otherwise Ill forget it here.
